# publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50


# publish joint trajectory action -----------------------------
hitch_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: hitch_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}